project:
  type: website
  output-dir: docs

website:
  title: ML Research Analysis
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Documentation
        href: documentation.qmd
      - text: Tutorial
        href: tutorial.qmd
      - text: Report
        href: report.qmd

format:
  html:
    css: style.css
