project:
  type: website
  output-dir: docs

execute:
  enabled: true
  echo: true
  warning: true
  error: true

website:
  title: ML Research Analysis
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Documentation
        href: documentation.qmd
      - text: Tutorial
        href: tutorial.qmd
      - text: Report
        href: report.qmd
      - text: Streamlit App
      - text: GitHub
        href: https://github.com/dallinmj/ml_research_trends

format:
  html:
    css: style.css
